### ISSUE TITLE
Kreiranje subjekta Beauty

### ISSUE THREAD

**Issue by speedz3107** [rmunk/EleventhHourBackend#2]
![screenshot_20170408-143326](https://cloud.githubusercontent.com/assets/23297219/24828941/60e973de-1c68-11e7-9687-4fa2d3b86188.png)
U admin panelu kod kreiranja subjekta u bjuti segmentu trazi da odaberes podkategoriju ali ti ne nudi nista za izabrati pa nemozes kreirati item.
![screenshot_20170408-142910](https://cloud.githubusercontent.com/assets/23297219/24828912/066aba1c-1c68-11e7-9ad3-cba815b2dd84.png)

**Comment by rmunk** [comment]
To je zato sta u _Beauty_ kategoriji nema niti jedne podkategorije, a odabir podkategorije je obavezan prilikom kreiranja providera. Prvo dodaj zeljenu podkategoriju u kategoriju _Beauty_ pa onda napravi providera.

**Comment by speedz3107** [comment]
Aaaaa...ok.
Sve jasno...
